services:
  web:
    build: .
    container_name: blog_web
    command: python mysite/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/blog
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: blog_postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: blog_redis

  worker:
    build: .
    container_name: blog_worker
    command: celery -A mysite.celery worker --loglevel=info
    working_dir: /app/mysite
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/blog_db
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:

