services:
  web:
    build: .
    container_name: blog_web
    command: sh -c "python mysite/manage.py migrate && python mysite/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "django-insecure-demo-key-for-docker-dev"
      DATABASE_URL: postgres://postgres:postgres@db:5432/blog_db
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:16
    container_name: blog_db
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blog_db"]
      interval: 3s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: blog_redis

  worker:
    build: .
    container_name: blog_worker
    command: celery -A mysite.celery worker --loglevel=info
    working_dir: /app/mysite
    environment:
      SECRET_KEY: "django-insecure-demo-key-for-docker-dev"
      DATABASE_URL: postgres://postgres:postgres@db:5432/blog_db
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data: